name: viscon_hackathon_app
description: Engage in collaborative learning, effectively and without the social awkwardness! NerdHerd - your study group finder
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  tuple: ^2.0.1
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  rive: ^0.9.1
  universal_platform: ^1.0.0+1
  page_transition: ^2.0.9
  cloud_firestore: ^4.11.0
  cloud_functions: ^4.5.1
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: .dart_tool/flutter_gen/gen/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#333333"
    theme_color: "#47759A"

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Baloo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
          weight: 800
