name: viscon_hackathon_app
description: Engage in collaborative learning, effectively and without the social awkwardness! NerdHerd - your study group finder
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  tuple: ^2.0.1
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  rive: ^0.9.1
  universal_platform: ^1.0.0+1
  firebase_core: ^2.7.0
  firebase_database: ^10.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  build_runner:
  flutter_gen_runner:

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

